---
abstract: 'compare two files character by character'
author:
  - 'Jeremy Mates <jmates@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Cmp
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
  Test::More: 0
  perl: 5.01
resources:
  homepage: http://github.com/thrig/File-Cmp
  license: http://dev.perl.org/licenses/
  repository: http://github.com/thrig/File-Cmp
version: 1.06
